#data initialisation and package loading

library(Seurat)
library(dyno)
library(ggplot2)
library(dplyr)
plot_data <- read.csv('/home/ivan/Desktop/Project2/MyData/paper/full_mature_exdata.csv',header=TRUE,sep=",")
rownames(plot_data) = plot_data$cell
colnames(plot_data)
factors <- read.csv('/home/ivan/Desktop/Project2/MyData/paper/factors.csv',header=TRUE,sep=",")
new_data = t(plot_data[,2:9961])
rownames(factors) = factors$cell
seurat_paper <- CreateSeuratObject(counts = new_data,meta.data=factors, min.cells = 3, min.features = 1, project = "my_scRNAseq")
Idents(seurat_paper) <- "group"
dim(seurat_paper)

#generate the F-set
allmarkers = FindAllMarkers(seurat_paper,assay="RNA")
lst_t=c()
group_1=c('CD69-DP','CD69+DP','CD4+CD8low','CD4SP_mature','CD8SP')
for (i in 1:(length(group_1)-1)){
  for (j in (i+1):length(group_1)){
    markers.all = FindMarkers(seurat_paper,assay="RNA",ident.1=group_1[i],ident.2=group_1[j])
    lst1=rownames(markers.all[order(markers.all['p_val'])[1:24],])
    lst_t = unique(c(lst1,lst_t))
  }
}
length(lst_t)
write.table(lst_t, '/home/ivan/Desktop/Project2/MyData/pipeline/seurat_degene2.txt', row.names=FALSE, quote=FALSE, sep='\t')



#read the Z-set generated by python
lst_drode <- read.csv('/home/ivan/Desktop/Project2/MyData/pipeline/degenes_drode.csv',header=TRUE,sep=",")
lst_drode = c(as.vector(lst_drode[,2]))
for(i in 1:length(lst_drode)){
  if(!lst_drode[i] %in% colnames(t(new_data))){
    print(lst_drode[i])
    lst_drode[i]=gsub("-", ".", lst_drode[i])
  }
  if(!lst_drode[i] %in% colnames(t(new_data))){
    print('wrong')
  }
}

#plot the trajectory using slingshot
dataset <- wrap_expression(
  counts = t(new_data)[,lst_drode],
  expression = t(new_data)[,lst_drode]
)
model <- infer_trajectory(dataset, 'slingshot')
model <- model %>% add_dimred(dyndimred::dimred_mds, expression_source = dataset$expression)
plot_dimred(
  model, 
  expression_source = dataset$expression, 
  grouping = factors$group
)



# evaluate the gene set using t-test.

zset = c(0.8571428571428572,
          0.8571428571428572,
          0.8571428571428572,
          0.8809523809523809,
          0.8690476190476191,
          0.8571428571428572,
          0.9047619047619048,
          0.8452380952380952,
          0.8571428571428572,
          0.8809523809523809,
          0.8690476190476191,
          0.7857142857142857,
          0.8690476190476191,
          0.8928571428571429,
          0.9166666666666666,
          0.8571428571428572,
          0.9047619047619048,
          0.8809523809523809,
          0.8452380952380952,
          0.8571428571428572)
fset = c(0.8928571428571429,
         0.8452380952380952,
         0.8452380952380952,
         0.9047619047619048,
         0.8095238095238095,
         0.8571428571428572,
         0.8928571428571429,
         0.7738095238095238,
         0.8452380952380952,
         0.7857142857142857,
         0.8333333333333334,
         0.8571428571428572,
         0.7976190476190477,
         0.8809523809523809,
         0.9166666666666666,
         0.8452380952380952,
         0.8214285714285714,
         0.8333333333333334,
         0.8333333333333334,
         0.9166666666666666)

kset=c(0.8095238095238095,
       0.8214285714285714,
       0.7142857142857143,
       0.7619047619047619,
       0.7142857142857143,
       0.7976190476190477,
       0.7738095238095238,
       0.7619047619047619,
       0.7619047619047619,
       0.8333333333333334,
       0.7976190476190477,
       0.7380952380952381,
       0.7738095238095238,
       0.7619047619047619,
       0.7857142857142857,
       0.8095238095238095,
       0.8095238095238095,
       0.7976190476190477,
       0.7380952380952381,
       0.7619047619047619)

mset = c(0.7857142857142857,
         0.7738095238095238,
         0.7738095238095238,
         0.8571428571428572,
         0.8690476190476191,
         0.8690476190476191,
         0.7857142857142857,
         0.7738095238095238,
         0.8095238095238095,
         0.8095238095238095,
         0.8690476190476191,
         0.8928571428571429,
         0.8095238095238095,
         0.8690476190476191,
         0.8214285714285714,
         0.7857142857142857,
         0.7619047619047619,
         0.8214285714285714,
         0.7976190476190477,
         0.7857142857142857)

tset=c(0.5595238095238095,
       0.5833333333333333,
       0.48809523809523814,
       0.6071428571428572,
       0.5,
       0.5595238095238095,
       0.41666666666666663,
       0.5476190476190477,
       0.5238095238095238,
       0.5595238095238095,
       0.5357142857142857,
       0.5119047619047619,
       0.5357142857142857,
       0.48809523809523814,
       0.5714285714285714,
       0.5238095238095238,
       0.5476190476190477,
       0.5833333333333333,
       0.5357142857142857,
       0.5476190476190477)

rset=c(0.4285714285714286,
       0.3571428571428571,
       0.34523809523809523,
       0.33333333333333337,
       0.34523809523809523,
       0.3214285714285714,
       0.38095238095238093,
       0.25,
       0.34523809523809523,
       0.2857142857142857,
       0.3571428571428571,
       0.38095238095238093,
       0.3571428571428571,
       0.3214285714285714,
       0.3571428571428571,
       0.38095238095238093,
       0.44047619047619047,
       0.30952380952380953,
       0.2857142857142857,
       0.3928571428571429)
t.test(zset,tset,var.equal = FALSE,alternative = 'greater')
